# Generated by Django 4.1.5 on 2023-09-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_year', models.IntegerField()),
                ('company_role', models.CharField(max_length=100)),
                ('post_username', models.CharField(max_length=100)),
                ('post_time', models.CharField(max_length=100)),
                ('tips', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
