# Generated by Django 4.1.5 on 2023-09-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_year', models.IntegerField()),
                ('post_time', models.CharField(max_length=100)),
                ('tips', models.TextField()),
            ],
        ),
    ]
