# Generated by Django 4.1.5 on 2023-09-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='company_role',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='company_year',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='post_time',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='post_username',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='tips',
        ),
    ]
