# Generated by Django 4.1.5 on 2023-09-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='experince',
            name='post_username',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
