# Generated by Django 4.1.5 on 2023-09-09 12:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_user_experince_post_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='experince',
            name='rounds',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), default=1, size=None),
            preserve_default=False,
        ),
    ]
