# Generated by Django 4.2.5 on 2023-09-12 18:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_experience_role_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='rounds',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), size=2), default=1, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_role',
            field=models.CharField(max_length=200),
        ),
    ]
