# Generated by Django 4.1.5 on 2023-09-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_experince_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experince',
            name='tips',
            field=models.TextField(null=True),
        ),
    ]
