# Generated by Django 4.1.5 on 2023-09-09 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_experince_tips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experince',
            name='rounds',
        ),
    ]
